name: optenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyscipopt==4.3.0
  - pip
  - pip:
    - highspy~=1.5.3
    - pyomo~=6.6.1
    - plotly~=5.15.0
    - pydantic~=1.10.9
    - numpy~=1.25.0
